name: KillQuestPlugin
version: 1.0.1
main: com.digitalwm.killquest.KillQuestPlugin
api: [1.1.0]
commands:
  quests:
    description: "Opens the quest selection form."
    usage: "/quests"
  jumpgen:
    description: "Generates a random jumping puzzle."
    usage: "/jumpgen <length> <width> <height>"
    permission: killquest.jumpgen
    aliases: [jp, jumppuzzle]
  clearpuzzle:
    description: "Clear an area ahead of the puzzle"
    usage: "/clearpuzzle <length> <width> <height>"
    permission: killquest.clear

permissions:
  killquest.jumpgen:
    description: "Allows the player to generate a jump puzzle."
    default: op
  killquest.clear:
    description: "Allows the player to clear an area for jump puzzle."
    default: op